_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1 # Specify GPU by CUDA_VISIBLE_DEVICES=0
accelerator: dp
min_epochs: 1100
max_epochs: 1200

log_every_n_steps: 5
weights_summary: null
progress_bar_refresh_rate: 25
resume_from_checkpoint: null
precision : 16
num_sanity_val_steps : 2 # This does not work with dp, only with ddp
val_check_interval: 0.25
benchmark: True
overfit_batches: False
# profiler : "simple"
