# output paths for hydra logs
run:
  dir: logs/runs/${model.cfg.name}_${datamodule.cfg.name}_${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: logs/multiruns/${name}/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
job:
  name: ${model.cfg.name}_${datamodule.cfg.name}  # This determines the 
  env_set:
    EXAMPLE_VAR: "example_value"